"""
allowList/paises.py

Diccionario exhaustivo de nombres de países → código ISO 3166-1 alpha-2.
Cubre nombres en español, inglés, portugués, francés y alemán,
además de variantes y errores ortográficos comunes.

Fuente de referencia: ISO 3166-1 (249 países y territorios).
"""

PAIS_A_ISO: dict[str, str] = {
    # A
    'afganistán': 'AF', 'afghanistan': 'AF', 'afganistan': 'AF',
    'albania': 'AL', 'albanie': 'AL',
    'alemania': 'DE', 'germany': 'DE', 'deutschland': 'DE', 'allemagne': 'DE',
    'andorra': 'AD',
    'angola': 'AO',
    'antigua y barbuda': 'AG', 'antigua and barbuda': 'AG',
    'arabia saudita': 'SA', 'arabia saudí': 'SA', 'saudi arabia': 'SA',
    'argelia': 'DZ', 'algeria': 'DZ', 'algérie': 'DZ',
    'argentina': 'AR',
    'armenia': 'AM',
    'australia': 'AU',
    'austria': 'AT', 'österreich': 'AT',
    'azerbaiyán': 'AZ', 'azerbaijan': 'AZ',
    # B
    'bahamas': 'BS',
    'bahrein': 'BH', 'bahréin': 'BH', 'bahrain': 'BH',
    'bangladesh': 'BD',
    'barbados': 'BB',
    'bélgica': 'BE', 'belgica': 'BE', 'belgium': 'BE', 'belgique': 'BE', 'belgien': 'BE',
    'belice': 'BZ', 'belize': 'BZ',
    'benín': 'BJ', 'benin': 'BJ', 'bénin': 'BJ',
    'bielorrusia': 'BY', 'belarus': 'BY', 'biélorussie': 'BY',
    'birmania': 'MM', 'myanmar': 'MM',
    'bolivia': 'BO',
    'bosnia y herzegovina': 'BA', 'bosnia and herzegovina': 'BA', 'bosnie': 'BA',
    'botsuana': 'BW', 'botswana': 'BW',
    'brasil': 'BR', 'brazil': 'BR', 'brésil': 'BR',
    'brunéi': 'BN', 'brunei': 'BN',
    'bulgaria': 'BG', 'bulgarie': 'BG',
    'burkina faso': 'BF',
    'burundi': 'BI',
    'bután': 'BT', 'bhutan': 'BT',
    # C
    'cabo verde': 'CV', 'cape verde': 'CV',
    'camboya': 'KH', 'cambodia': 'KH', 'cambodge': 'KH',
    'camerún': 'CM', 'cameroon': 'CM', 'cameroun': 'CM',
    'canadá': 'CA', 'canada': 'CA',
    'catar': 'QA', 'qatar': 'QA',
    'chad': 'TD',
    'chile': 'CL',
    'china': 'CN',
    'chipre': 'CY', 'cyprus': 'CY', 'chypre': 'CY',
    'colombia': 'CO',
    'comoras': 'KM', 'comoros': 'KM', 'comores': 'KM',
    'congo': 'CG', 'república del congo': 'CG', 'republic of the congo': 'CG',
    'república democrática del congo': 'CD', 'democratic republic of the congo': 'CD', 'rdc': 'CD',
    'corea del norte': 'KP', 'north korea': 'KP',
    'corea del sur': 'KR', 'south korea': 'KR',
    'costa de marfil': 'CI', "côte d'ivoire": 'CI', 'ivory coast': 'CI',
    'costa rica': 'CR',
    'croacia': 'HR', 'croatia': 'HR', 'croatie': 'HR',
    'cuba': 'CU',
    # D
    'dinamarca': 'DK', 'denmark': 'DK', 'danemark': 'DK', 'dänemark': 'DK',
    'djibouti': 'DJ', 'yibuti': 'DJ',
    'dominica': 'DM',
    # E
    'ecuador': 'EC',
    'egipto': 'EG', 'egypt': 'EG', 'égypte': 'EG',
    'el salvador': 'SV',
    'emiratos árabes unidos': 'AE', 'uae': 'AE', 'united arab emirates': 'AE',
    'eritrea': 'ER',
    'eslovaquia': 'SK', 'slovakia': 'SK', 'slovaquie': 'SK',
    'eslovenia': 'SI', 'slovenia': 'SI', 'slovénie': 'SI',
    'españa': 'ES', 'espana': 'ES', 'spain': 'ES', 'espagne': 'ES', 'spanien': 'ES',
    'estados unidos': 'US', 'usa': 'US', 'united states': 'US', 'eeuu': 'US',
    'estonia': 'EE', 'estonie': 'EE',
    'etiopía': 'ET', 'ethiopia': 'ET', 'éthiopie': 'ET',
    # F
    'filipinas': 'PH', 'philippines': 'PH',
    'finlandia': 'FI', 'finland': 'FI', 'finlande': 'FI', 'finnland': 'FI',
    'fiyi': 'FJ', 'fiji': 'FJ',
    'francia': 'FR', 'france': 'FR', 'frankreich': 'FR',
    # G
    'gabón': 'GA', 'gabon': 'GA',
    'gambia': 'GM',
    'georgia': 'GE', 'géorgie': 'GE',
    'ghana': 'GH',
    'granada': 'GD', 'grenada': 'GD',
    'grecia': 'GR', 'greece': 'GR', 'grèce': 'GR', 'griechenland': 'GR',
    'guatemala': 'GT',
    'guinea': 'GN',
    'guinea ecuatorial': 'GQ', 'equatorial guinea': 'GQ',
    'guinea-bisáu': 'GW', 'guinea-bissau': 'GW',
    'guyana': 'GY',
    # H
    'haití': 'HT', 'haiti': 'HT',
    'honduras': 'HN',
    'hungría': 'HU', 'hungary': 'HU', 'hongrie': 'HU', 'ungarn': 'HU',
    # I
    'india': 'IN', 'inde': 'IN',
    'indonesia': 'ID',
    'irak': 'IQ', 'iraq': 'IQ',
    'irán': 'IR', 'iran': 'IR',
    'irlanda': 'IE', 'ireland': 'IE', 'irlande': 'IE',
    'islandia': 'IS', 'iceland': 'IS', 'islande': 'IS',
    'islas marshall': 'MH', 'marshall islands': 'MH',
    'islas salomón': 'SB', 'solomon islands': 'SB',
    'israel': 'IL',
    'italia': 'IT', 'italy': 'IT', 'italie': 'IT', 'italien': 'IT',
    # J
    'jamaica': 'JM',
    'japón': 'JP', 'japan': 'JP', 'japon': 'JP', 'japon': 'JP',
    'jordania': 'JO', 'jordan': 'JO', 'jordanie': 'JO',
    # K
    'kazajistán': 'KZ', 'kazakhstan': 'KZ',
    'kenia': 'KE', 'kenya': 'KE',
    'kirguistán': 'KG', 'kyrgyzstan': 'KG',
    'kiribati': 'KI',
    'kuwait': 'KW',
    # L
    'laos': 'LA',
    'lesoto': 'LS', 'lesotho': 'LS',
    'letonia': 'LV', 'latvia': 'LV', 'lettonie': 'LV',
    'líbano': 'LB', 'libano': 'LB', 'lebanon': 'LB', 'liban': 'LB',
    'liberia': 'LR',
    'libia': 'LY', 'libya': 'LY', 'libye': 'LY',
    'liechtenstein': 'LI',
    'lituania': 'LT', 'lithuania': 'LT', 'lituanie': 'LT',
    'luxemburgo': 'LU', 'luxembourg': 'LU',
    # M
    'madagascar': 'MG',
    'malasia': 'MY', 'malaysia': 'MY',
    'malaui': 'MW', 'malawi': 'MW',
    'maldivas': 'MV', 'maldives': 'MV',
    'malí': 'ML', 'mali': 'ML',
    'malta': 'MT',
    'marruecos': 'MA', 'morocco': 'MA', 'maroc': 'MA',
    'mauricio': 'MU', 'mauritius': 'MU',
    'mauritania': 'MR',
    'méxico': 'MX', 'mexico': 'MX',
    'micronesia': 'FM',
    'moldavia': 'MD', 'moldova': 'MD',
    'mónaco': 'MC', 'monaco': 'MC',
    'mongolia': 'MN',
    'montenegro': 'ME',
    'mozambique': 'MZ',
    # N
    'namibia': 'NA',
    'nauru': 'NR',
    'nepal': 'NP',
    'nicaragua': 'NI',
    'níger': 'NE', 'niger': 'NE',
    'nigeria': 'NG',
    'noruega': 'NO', 'norway': 'NO', 'norvège': 'NO', 'norwegen': 'NO',
    'nueva zelanda': 'NZ', 'new zealand': 'NZ', 'nouvelle-zélande': 'NZ',
    # O
    'omán': 'OM', 'oman': 'OM',
    # P
    'países bajos': 'NL', 'netherlands': 'NL', 'holanda': 'NL', 'holland': 'NL', 'pays-bas': 'NL', 'niederlande': 'NL',
    'pakistán': 'PK', 'pakistan': 'PK',
    'palaos': 'PW', 'palau': 'PW',
    'palestina': 'PS', 'palestine': 'PS',
    'panamá': 'PA', 'panama': 'PA',
    'papúa nueva guinea': 'PG', 'papua new guinea': 'PG',
    'paraguay': 'PY',
    'perú': 'PE', 'peru': 'PE', 'pérou': 'PE',
    'polonia': 'PL', 'poland': 'PL', 'pologne': 'PL', 'polen': 'PL',
    'portugal': 'PT',
    # R
    'reino unido': 'GB', 'united kingdom': 'GB', 'uk': 'GB', 'gran bretaña': 'GB', 'great britain': 'GB',
    'república centroafricana': 'CF', 'central african republic': 'CF',
    'república checa': 'CZ', 'czech republic': 'CZ', 'chequia': 'CZ', 'czechia': 'CZ',
    'república dominicana': 'DO', 'dominican republic': 'DO',
    'ruanda': 'RW', 'rwanda': 'RW',
    'rumanía': 'RO', 'romania': 'RO', 'roumanie': 'RO',
    'rusia': 'RU', 'russia': 'RU', 'russie': 'RU',
    # S
    'samoa': 'WS',
    'san cristóbal y nieves': 'KN', 'saint kitts and nevis': 'KN',
    'san marino': 'SM',
    'san vicente y las granadinas': 'VC', 'saint vincent and the grenadines': 'VC',
    'santa lucía': 'LC', 'saint lucia': 'LC',
    'santo tomé y príncipe': 'ST', 'sao tome and principe': 'ST',
    'senegal': 'SN', 'sénégal': 'SN',
    'serbia': 'RS',
    'seychelles': 'SC',
    'sierra leona': 'SL', 'sierra leone': 'SL',
    'singapur': 'SG', 'singapore': 'SG',
    'siria': 'SY', 'syria': 'SY', 'syrie': 'SY',
    'somalia': 'SO',
    'sri lanka': 'LK',
    'suazilandia': 'SZ', 'esuatini': 'SZ', 'eswatini': 'SZ',
    'sudáfrica': 'ZA', 'south africa': 'ZA', 'afrique du sud': 'ZA',
    'sudán': 'SD', 'sudan': 'SD',
    'sudán del sur': 'SS', 'south sudan': 'SS',
    'suecia': 'SE', 'sweden': 'SE', 'suède': 'SE', 'schweden': 'SE',
    'suiza': 'CH', 'switzerland': 'CH', 'suisse': 'CH', 'schweiz': 'CH',
    'surinam': 'SR', 'suriname': 'SR',
    # T
    'tailandia': 'TH', 'thailand': 'TH', 'thaïlande': 'TH',
    'tanzania': 'TZ',
    'tayikistán': 'TJ', 'tajikistan': 'TJ',
    'timor oriental': 'TL', 'east timor': 'TL', 'timor-leste': 'TL',
    'togo': 'TG',
    'tonga': 'TO',
    'trinidad y tobago': 'TT', 'trinidad and tobago': 'TT',
    'túnez': 'TN', 'tunisia': 'TN', 'tunisie': 'TN',
    'turkmenistán': 'TM', 'turkmenistan': 'TM',
    'turquía': 'TR', 'turkey': 'TR', 'turquie': 'TR', 'türkei': 'TR',
    'tuvalu': 'TV',
    # U
    'ucrania': 'UA', 'ukraine': 'UA', 'ukraine': 'UA',
    'uganda': 'UG',
    'uruguay': 'UY',
    'uzbekistán': 'UZ', 'uzbekistan': 'UZ',
    # V
    'vanuatu': 'VU',
    'vaticano': 'VA', 'vatican': 'VA', 'holy see': 'VA',
    'venezuela': 'VE',
    'vietnam': 'VN', 'viet nam': 'VN',
    # Y
    'yemen': 'YE',
    'yibuti': 'DJ', 'djibouti': 'DJ',
    # Z
    'zambia': 'ZM',
    'zimbabue': 'ZW', 'zimbabwe': 'ZW',
}


def resolver_iso_pais(pais_raw: str) -> str | None:
    """
    Resuelve el nombre de un país escrito libremente a su código ISO 3166-1 alpha-2.
    La búsqueda es insensible a mayúsculas y tildes comunes.
    Devuelve el código (ej. 'ES') o None si no se reconoce.
    """
    clave = pais_raw.strip().lower()
    return PAIS_A_ISO.get(clave)