# Generated by Django 5.2.11 on 2026-02-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_ia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('respuesta', models.JSONField()),
                ('momento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
