# Generated by Django 5.2.11 on 2026-04-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_ia',
            name='duracion_generacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial_ia',
            name='duracion_optimizacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial_ia',
            name='duracion_scoring',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial_ia',
            name='duracion_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial_ia',
            name='duracion_validacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial_ia',
            name='estado_tarea',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='historial_ia',
            name='etapa_actual',
            field=models.CharField(default='pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='historial_ia',
            name='mensaje_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial_ia',
            name='sesion_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
