# Generated by Django 5.2.11 on 2026-04-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion', '0002_historial_ia_duracion_generacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_ia',
            name='sesion_generacion_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
