# Generated by Django 5.2.11 on 2026-04-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion', '0003_historial_ia_sesion_generacion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_ia',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
