# Generated by Django 5.2.11 on 2026-03-31 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('rutas', '0005_parada_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ia_route_generation', 'IA Route Generation'), ('ia_stop_replacement', 'IA Stop Replacement')], max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_usage_events', to='rutas.guia')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tier_usage_events', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Tier Usage Event',
                'verbose_name_plural': 'Tier Usage Events',
                'db_table': 'billing_tier_usage_event',
                'indexes': [models.Index(fields=['guia', 'action', 'created_at'], name='billing_tie_guia_id_f835c1_idx'), models.Index(fields=['guia', 'ruta', 'action', 'created_at'], name='billing_tie_guia_id_79d644_idx')],
            },
        ),
    ]
