# Generated by Django 5.2.11 on 2026-04-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_tierusageevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureAccessSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('availability', models.CharField(choices=[('freemium', 'Freemium'), ('premium', 'Premium'), ('both', 'Freemium y Premium')], default='both', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Access Setting',
                'verbose_name_plural': 'Feature Access Settings',
                'db_table': 'billing_feature_access_setting',
                'indexes': [models.Index(fields=['availability'], name='billing_fea_availab_5fd1d8_idx')],
            },
        ),
    ]
