# Generated by Django 5.2.11 on 2026-04-13 22:37

from django.db import migrations, models


def _migrate_availability_to_flags(apps, schema_editor):
    FeatureAccessSetting = apps.get_model('billing', 'FeatureAccessSetting')
    for row in FeatureAccessSetting.objects.all():
        availability = str(getattr(row, 'availability', '') or '').strip().lower()
        if availability == 'freemium':
            row.enabled_freemium = True
            row.enabled_premium = False
        elif availability == 'premium':
            row.enabled_freemium = False
            row.enabled_premium = True
        elif availability == 'both':
            row.enabled_freemium = True
            row.enabled_premium = True
        row.save(update_fields=['enabled_freemium', 'enabled_premium'])


def _migrate_flags_to_availability(apps, schema_editor):
    FeatureAccessSetting = apps.get_model('billing', 'FeatureAccessSetting')
    for row in FeatureAccessSetting.objects.all():
        freemium = bool(getattr(row, 'enabled_freemium', False))
        premium = bool(getattr(row, 'enabled_premium', False))
        if freemium and premium:
            row.availability = 'both'
        elif freemium and not premium:
            row.availability = 'freemium'
        elif premium and not freemium:
            row.availability = 'premium'
        else:
            # El esquema antiguo no soportaba "off/off": degradamos a "both".
            row.availability = 'both'
        row.save(update_fields=['availability'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_featureaccesssetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureaccesssetting',
            name='enabled_freemium',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featureaccesssetting',
            name='enabled_premium',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            _migrate_availability_to_flags,
            _migrate_flags_to_availability,
        ),
        migrations.RemoveIndex(
            model_name='featureaccesssetting',
            name='billing_fea_availab_5fd1d8_idx',
        ),
        migrations.RemoveField(
            model_name='featureaccesssetting',
            name='availability',
        ),
    ]
