# Generated by Django 5.2.11 on 2026-03-10 22:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('categoria', models.CharField(choices=[('tourism=museum', 'Museo'), ('historic=monument', 'Monumento'), ('amenity=restaurant', 'Restaurante'), ('amenity=cafe', 'Café'), ('amenity=bar', 'Bar'), ('amenity=place_of_worship', 'Lugar de culto'), ('leisure=park', 'Parque'), ('amenity=theatre', 'Teatro'), ('amenity=library', 'Biblioteca'), ('tourism=gallery', 'Galería de arte'), ('tourism=hotel', 'Hotel'), ('tourism=viewpoint', 'Mirador'), ('historic=castle', 'Castillo'), ('historic=ruins', 'Ruinas'), ('amenity=marketplace', 'Mercado'), ('place=square', 'Plaza'), ('amenity=cinema', 'Cine'), ('leisure=stadium', 'Estadio'), ('other', 'Otro')], db_index=True, default='other', max_length=60)),
                ('coordenadas', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('ciudad', models.CharField(blank=True, db_index=True, max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('fuente', models.CharField(choices=[('osm', 'OpenStreetMap'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('osm_id', models.BigIntegerField(blank=True, help_text='ID del elemento en OpenStreetMap (nulo para entradas manuales).', null=True, unique=True)),
                ('osm_type', models.CharField(blank=True, help_text='Tipo OSM: node, way o relation.', max_length=10)),
            ],
            options={
                'verbose_name': 'POI (Allowlist)',
                'verbose_name_plural': 'POIs (Allowlist)',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['ciudad', 'categoria'], name='allowList_p_ciudad_21c954_idx')],
            },
        ),
    ]
