# Generated by Django 5.2.11 on 2026-04-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowList', '0001_allow_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='fuente',
            field=models.CharField(choices=[('osm', 'OpenStreetMap'), ('manual', 'Manual'), ('google', 'Google Places')], default='manual', max_length=10),
        ),
    ]
