# Generated by Django 5.2.11 on 2026-05-04 21:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowList', '0002_add_google_fuente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=120, unique=True)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Límite oficial de ciudad',
                'verbose_name_plural': 'Límites oficiales de ciudades',
                'ordering': ['city_name'],
            },
        ),
        migrations.AddField(
            model_name='poi',
            name='google_last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Última fecha en la que el POI apareció en SearchText.', null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='google_place_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de lugar devuelto por Google Places v1 (places/{id}).', max_length=128),
        ),
        migrations.AddField(
            model_name='poi',
            name='google_rank_position',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Posición de ranking devuelta por Google SearchText (1 = más relevante).', null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='google_search_query',
            field=models.CharField(blank=True, help_text='Consulta de SearchText utilizada para descubrir el POI.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['ciudad', 'google_rank_position'], name='allowList_p_ciudad_b05e78_idx'),
        ),
    ]
