# Generated by Django 5.2.11 on 2026-02-22 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RUTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TURISTA',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('alias', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SESION_TOUR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_acceso', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.ruta')),
                ('turistas', models.ManyToManyField(to='tours.turista')),
            ],
        ),
        migrations.CreateModel(
            name='UBICACION_VIVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas_lat', models.FloatField(blank=True, null=True)),
                ('coordenadas_lon', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('sesion_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.sesion_tour')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
