# Generated by Django 5.2.11 on 2026-03-02 18:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0002_alter_parada_orden_alter_ruta_duracion_horas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SESION_TOUR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_acceso', models.CharField(max_length=50, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('parada_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_actuales', to='rutas.parada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='rutas.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='MENSAJE_CHAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('momento', models.DateTimeField(auto_now_add=True)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sesion_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='tours.sesion_tour')),
            ],
        ),
        migrations.CreateModel(
            name='TURISTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TURISTASESION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('sesion_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.sesion_tour')),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.turista')),
            ],
            options={
                'unique_together': {('turista', 'sesion_tour')},
            },
        ),
        migrations.AddField(
            model_name='sesion_tour',
            name='turistas',
            field=models.ManyToManyField(blank=True, through='tours.TURISTASESION', to='tours.turista'),
        ),
        migrations.CreateModel(
            name='UBICACION_VIVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('timestamp', models.DateTimeField()),
                ('sesion_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.sesion_tour')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
