# Generated by Django 5.2.11 on 2026-03-01 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion_tour',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='PARTICIPANT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('sesion_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='tours.sesion_tour')),
            ],
            options={
                'unique_together': {('alias', 'sesion_tour')},
            },
        ),
    ]
