# Generated by Django 5.2.11 on 2026-02-22 21:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion_vivo',
            name='coordenadas_lat',
        ),
        migrations.RemoveField(
            model_name='ubicacion_vivo',
            name='coordenadas_lon',
        ),
        migrations.AddField(
            model_name='ubicacion_vivo',
            name='coordenadas',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
