# Generated by Django 5.2.11 on 2026-03-01 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_sesion_tour_token_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion_tour',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
