# Generated by Django 5.2.11 on 2026-03-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_rename_models_to_pascalcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesiontour',
            name='turistas',
            field=models.ManyToManyField(blank=True, through='tours.TuristaSesion', to='tours.turista'),
        ),
        migrations.AlterModelTable(
            name='turista',
            table='tours_turista',
        ),
        migrations.AlterModelTable(
            name='turistasesion',
            table='tours_turistasesion',
        ),
    ]
