# Generated by Django 5.2.11 on 2026-02-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_ubicacion_vivo_coordenadas_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion_tour',
            name='ruta',
        ),
        migrations.DeleteModel(
            name='RUTA',
        ),
    ]
