# Generated by Django 5.2.11 on 2026-03-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
        ('tours', '0002_mensaje_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion_tour',
            name='ruta',
            field=models.ForeignKey(
                default=1,  # Temporalmente usa ID 1 (ajusta según tu primera ruta)
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sesiones',
                to='rutas.ruta'
            ),
            preserve_default=False,
        ),
    ]