# Generated by Django 5.2.11 on 2026-03-01 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def migrate_turista_data(apps, schema_editor):
    """
    Migrar datos del modelo TURISTA antiguo al nuevo,
    y GUARDAR las relaciones M2M antes de que se eliminen
    """
    TURISTA_old = apps.get_model('tours', 'TURISTA')
    TURISTA_new = apps.get_model('tours', 'TURISTA_NEW')
    SESION_TOUR = apps.get_model('tours', 'SESION_TOUR')
    db_alias = schema_editor.connection.alias
    
    # Guardar las relaciones M2M ANTES de que se eliminen
    # Esto es crítico porque RemoveField eliminará la tabla intermedia
    m2m_data = []
    for sesion in SESION_TOUR.objects.using(db_alias).all():
        for turista in sesion.turistas.using(db_alias).all():
            m2m_data.append({
                'sesion_id': sesion.id,
                'user_id': turista.user_id,
                'alias': turista.alias
            })
    
    # Copiar todos los turistas al nuevo modelo
    user_to_new_id = {}
    for old_turista in TURISTA_old.objects.using(db_alias).all():
        new_turista = TURISTA_new.objects.using(db_alias).create(
            alias=old_turista.alias,
            user=old_turista.user
        )
        user_to_new_id[old_turista.user_id] = new_turista.id
    
    # Guardar el mapeo en una tabla temporal para usarlo después
    # Como no podemos pasar variables entre operaciones, usaremos
    # una tabla temporal en la base de datos
    with schema_editor.connection.cursor() as cursor:
        # Crear tabla temporal para guardar las relaciones M2M
        cursor.execute("""
            CREATE TEMPORARY TABLE IF NOT EXISTS _temp_m2m_turista_sesion (
                sesion_id INTEGER,
                new_turista_id INTEGER
            )
        """)
        
        # Insertar las relaciones mapeadas
        for relation in m2m_data:
            new_turista_id = user_to_new_id.get(relation['user_id'])
            if new_turista_id:
                cursor.execute(
                    "INSERT INTO _temp_m2m_turista_sesion (sesion_id, new_turista_id) VALUES (%s, %s)",
                    [relation['sesion_id'], new_turista_id]
                )


def migrate_m2m_to_turistasesion(apps, schema_editor):
    """
    Restaurar las relaciones M2M desde la tabla temporal a TURISTASESION
    """
    TURISTASESION = apps.get_model('tours', 'TURISTASESION')
    db_alias = schema_editor.connection.alias
    
    # Leer de la tabla temporal y crear registros en TURISTASESION
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute("SELECT sesion_id, new_turista_id FROM _temp_m2m_turista_sesion")
            rows = cursor.fetchall()
            
            # Crear registros en TURISTASESION
            for sesion_id, turista_id in rows:
                # Usar get_or_create para evitar duplicados
                TURISTASESION.objects.using(db_alias).get_or_create(
                    sesion_tour_id=sesion_id,
                    turista_id=turista_id,
                    defaults={'activo': True}
                )
            
            # Limpiar la tabla temporal
            cursor.execute("DROP TABLE IF EXISTS _temp_m2m_turista_sesion")
        except Exception as e:
            # Si no existe la tabla temporal, simplemente continuar
            # Esto puede pasar en reversiones o en bases de datos ya migradas
            pass


def reverse_migrate_turista_data(apps, schema_editor):
    """
    Función de reversión - no se puede revertir completamente sin backup
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_sesion_tour_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Paso 1: Crear el nuevo modelo TURISTA con nombre temporal
        migrations.CreateModel(
            name='TURISTA_NEW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tours_turista_new',
            },
        ),
        
        # Paso 2: Copiar datos del modelo antiguo al nuevo (antes de eliminar)
        migrations.RunPython(migrate_turista_data, reverse_migrate_turista_data),
        
        # Paso 3: Eliminar la relación ManyToMany actual (esto elimina la tabla intermedia)
        migrations.RemoveField(
            model_name='sesion_tour',
            name='turistas',
        ),
        
        # Paso 4: Eliminar el modelo TURISTA antiguo
        migrations.DeleteModel(
            name='TURISTA',
        ),
        
        # Paso 5: Renombrar TURISTA_NEW a TURISTA
        migrations.RenameModel(
            old_name='TURISTA_NEW',
            new_name='TURISTA',
        ),
        
        # Paso 6: Actualizar el nombre de la tabla a la correcta
        migrations.AlterModelTable(
            name='turista',
            table=None,  # Esto usa el nombre por defecto: tours_turista
        ),
        
        # Paso 7: Crear tabla intermedia TURISTASESION 
        migrations.CreateModel(
            name='TURISTASESION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('sesion_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.sesion_tour')),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.turista')),
            ],
            options={
                'unique_together': {('turista', 'sesion_tour')},
            },
        ),
        
        # Paso 8: Migrar relaciones M2M a TURISTASESION (si es posible)
        migrations.RunPython(migrate_m2m_to_turistasesion, migrations.RunPython.noop),
        
        # Paso 9: Agregar la relación ManyToMany con through
        migrations.AddField(
            model_name='sesion_tour',
            name='turistas',
            field=models.ManyToManyField(blank=True, through='tours.TURISTASESION', to='tours.turista'),
        ),
    ]
