# Generated by Django 5.2.11 on 2026-03-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0003_alter_sesiontour_turistas_alter_turista_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ubicacionvivo",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.user",
            ),
        ),
        migrations.AddField(
            model_name="ubicacionvivo",
            name="turista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ubicaciones_vivas",
                to="tours.turista",
            ),
        ),
    ]
