# Generated by Django 5.2.11 on 2026-03-01 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_turista_data(apps, schema_editor):
    # Guardar datos de turistas antes del cambio
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_sesion_tour_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Eliminar la relación ManyToMany actual
        migrations.RemoveField(
            model_name='sesion_tour',
            name='turistas',
        ),

        # Eliminar el modelo TURISTA completamente para recrearlo
        migrations.DeleteModel(
            name='TURISTA',
        ),
        # Recrear TURISTA con nuevo esquema
        migrations.CreateModel(
            name='TURISTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # Crear tabla intermedia TURISTASESION 
        migrations.CreateModel(
            name='TURISTASESION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('sesion_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.sesion_tour')),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.turista')),
            ],
            options={
                'unique_together': {('turista', 'sesion_tour')},
            },
        ),
        # Agregar la relación ManyToMany con through
        migrations.AddField(
            model_name='sesion_tour',
            name='turistas',
            field=models.ManyToManyField(blank=True, through='tours.TURISTASESION', to='tours.turista'),
        ),
    ]
