# Generated by Django 5.2.11 on 2026-02-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_sesion_tour_ruta_delete_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion_tour',
            name='turistas',
            field=models.ManyToManyField(blank=True, to='tours.turista'),
        ),
    ]
