# Generated by Django 5.2.11 on 2026-03-01 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_alter_parada_orden_alter_ruta_duracion_horas_and_more'),
        ('tours', '0004_restructure_turista'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion_tour',
            name='parada_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_actuales', to='rutas.parada'),
        ),
    ]
