# Generated by Django 5.2.11 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_ubicacionvivo_turista_nullable_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensajechat",
            name="imagen",
            field=models.FileField(blank=True, null=True, upload_to="chat_mensajes/%Y/%m/%d/"),
        ),
    ]
