# Generated by Django 5.2.11 on 2026-04-07 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_mensajechat_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajechat',
            name='destinatario_turista',
            field=models.ForeignKey(blank=True, help_text='Destinatario cuando el guía envía un mensaje privado a un turista concreto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos_privados', to='tours.turista'),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='es_privado',
            field=models.BooleanField(db_index=True, default=False, help_text='True para mensajes del canal privado Guía ↔ Turista individual.'),
        ),
        migrations.AddIndex(
            model_name='mensajechat',
            index=models.Index(fields=['sesion_tour', 'es_privado', 'momento'], name='tours_mensa_sesion__a82f19_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajechat',
            index=models.Index(fields=['sesion_tour', 'turista', 'destinatario_turista'], name='tours_mensa_sesion__a93933_idx'),
        ),
    ]
