# Generated by Django 5.2.11 on 2026-03-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_ubicacionvivo_turista_nullable_usuario'),
        ('tours', '0005_repair_mensaje_chat_remitente_nullable'),
    ]

    operations = [
    ]
