# Generated by Django 5.2.11 on 2026-04-13 18:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_chat_privado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordatorioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('hora_objetivo', models.DateTimeField()),
                ('avisar_minutos_antes', models.PositiveIntegerField(default=10)),
                ('ubicacion_quedada', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('etiqueta_quedada', models.CharField(blank=True, default='', max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_creados', to=settings.AUTH_USER_MODEL)),
                ('sesion_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='tours.sesiontour')),
            ],
            options={
                'verbose_name': 'Recordatorio de Sesión',
                'verbose_name_plural': 'Recordatorios de Sesión',
                'db_table': 'tours_recordatorio_sesion',
                'ordering': ['hora_objetivo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EntregaRecordatorioTurista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado_en', models.DateTimeField(auto_now_add=True)),
                ('recordatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='tours.recordatoriosesion')),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_entregados', to='tours.turista')),
            ],
            options={
                'verbose_name': 'Entrega de Recordatorio',
                'verbose_name_plural': 'Entregas de Recordatorio',
                'db_table': 'tours_entrega_recordatorio_turista',
            },
        ),
        migrations.AddIndex(
            model_name='recordatoriosesion',
            index=models.Index(fields=['sesion_tour', 'activo', 'hora_objetivo'], name='tours_recor_sesion__272d0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='entregarecordatorioturista',
            constraint=models.UniqueConstraint(fields=('recordatorio', 'turista'), name='unique_recordatorio_turista_entrega'),
        ),
    ]
