# Generated by Django 5.2.11 on 2026-03-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_delete_participant'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='PARTICIPANT',
                ),
            ],
        ),
    ]
