# Generated by Django 5.2.11 on 2026-03-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_add_ruta_column'),
        ('tours', '0007_delete_participant'),
    ]

    operations = [
    ]
