# Generated by Django 5.2.11 on 2026-04-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_recordatorios_sesion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recordatoriosesion',
            new_name='tours_recor_sesion__31f651_idx',
            old_name='tours_recor_sesion__272d0f_idx',
        ),
    ]
