# Generated by Django 5.2.11 on 2026-03-02 16:41

from django.db import migrations


def delete_participant_if_exists(apps, schema_editor):
    """
    Eliminar el modelo PARTICIPANT solo si la tabla existe en la base de datos.
    Esto previene errores cuando la tabla nunca fue creada o ya fue eliminada.
    """
    with schema_editor.connection.cursor() as cursor:
        # Verificar si la tabla existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'tours_participant'
            );
        """)
        table_exists = cursor.fetchone()[0]
        
        if table_exists:
            # Si la tabla existe, eliminarla
            cursor.execute("DROP TABLE tours_participant CASCADE;")


def reverse_delete_participant(apps, schema_editor):
    """
    No se puede revertir la eliminación sin backup de datos.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_delete_participant'),
    ]

    operations = [
        migrations.RunPython(delete_participant_if_exists, reverse_delete_participant),
    ]
