# Generated by Django 5.2.11 on 2026-03-02 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_update_mensaje_chat_for_anonymous'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='mensaje_chat',
                    name='turista',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='tours.turista'),
                ),
            ],
        ),
    ]
