# Usamos la imagen oficial de pgvector
FROM ankane/pgvector:latest

# Instalamos PostGIS (usando la variable de entorno $PG_MAJOR que ya trae la imagen)
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       postgresql-$PG_MAJOR-postgis-3 \
       postgresql-$PG_MAJOR-postgis-3-scripts \
       postgis \
    && rm -rf /var/lib/apt/lists/*