# Generated by Django 5.2.11 on 2026-02-25 15:54

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_suscripcion', models.CharField(choices=[('Freemium', 'Freemium'), ('Premium', 'Premium')], default='Freemium', max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guia', to='rutas.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion_horas', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('num_personas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('nivel_exigencia', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=50)),
                ('mood', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Historia', 'Historia'), ('Gastronomía', 'Gastronomía'), ('Naturaleza', 'Naturaleza'), ('Misterio y Leyendas', 'Misterio y Leyendas'), ('Local', 'Local'), ('Cine y Series', 'Cine y Series'), ('Religioso y Espiritual', 'Religioso y Espiritual'), ('Arquitectura y Diseño', 'Arquitectura y Diseño'), ('Ocio/Cultural', 'Ocio/Cultural')], max_length=25), default=list, size=None)),
                ('es_generada_ia', models.BooleanField(default=False)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='rutas.guia')),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('nombre', models.CharField(max_length=255)),
                ('coordenadas', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='rutas.ruta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.CheckConstraint(condition=models.Q(('duracion_horas__gte', 0.0)), name='duracion_horas_positiva'),
        ),
    ]
