# Generated by Django 5.2.11 on 2026-02-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='orden',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='duracion_horas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='num_personas',
            field=models.PositiveIntegerField(),
        ),
    ]
