# Generated by Django 5.2.11 on 2026-03-10 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_add_graphhopper_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curiosidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('Historia', 'Historia'), ('Arquitectura', 'Arquitectura'), ('Personaje', 'Personaje'), ('Evento', 'Evento'), ('Dato Curioso', 'Dato Curioso')], default='Dato Curioso', max_length=25)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('parada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curiosidad', to='rutas.parada')),
            ],
            options={
                'verbose_name': 'Curiosidad',
                'verbose_name_plural': 'Curiosidades',
            },
        ),
    ]
