# Generated by Django 5.2.11 on 2026-03-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_curiosidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción breve de la parada...'),
        ),
    ]
