# Generated by Django 5.2.11 on 2026-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0005_parada_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curiosidad',
            name='imagen_manual',
            field=models.ImageField(blank=True, null=True, upload_to='curiosidades_manual/%Y/%m/%d/'),
        ),
    ]
