# Generated by Django 5.2.11 on 2026-04-12 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0005_parada_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parada_id_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('parada_nombre_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('parada_orden_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_evento', models.CharField(choices=[('parada_anadida', 'Parada añadida'), ('parada_modificada', 'Parada modificada'), ('parada_eliminada', 'Parada eliminada'), ('paradas_reordenadas', 'Paradas reordenadas')], max_length=40)),
                ('motivo', models.TextField(blank=True, default='')),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('parada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutas.parada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='rutas.ruta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
    ]
